version: '3.5'
# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
    mysql:
        image: mysql:latest
        ports:
            - "${MYSQL_PORT}:3306"
        restart: always
        environment:
            - TZ=${TZ}
            - MYSQL_USER=mysql                               # 设置 Mysql 用户名称
            - MYSQL_PASSWORD=${COMMON_PASSWORD}              # 设置 Mysql 用户密码
            - MYSQL_ROOT_PASSWORD=${COMMON_PASSWORD}         # 设置 Mysql root 用户密码
        volumes:
            - ./data/mysql/data:/var/lib/mysql
        networks:
            - backend

    redis:
        ports:
            - "${REDIS_PORT}:6379"
        image: redis
        restart: always
        networks:
            - backend

    nginx:
        image: nginx
        environment:
            - TZ=${TZ}
        volumes:
            - ./data/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./data/nginx/logs:/var/log/nginx
            - ./data/nginx/www:/usr/share/nginx
            - ./data/nginx/config/conf.d:/etc/nginx/conf.d
            - ./data/nginx/ssh:/root/.ssh
        ports:
            - "80:80"
        networks:
            - backend
        restart: always
